insert into devices (name, cat) values ('Tesla 2017 Red', 'other');
insert into devices (name, cat) values ('Tesla 2019 White', 'other');
insert into devices (name, cat) values ('iBike e-Assist', 'other');
insert into devices (name, cat) values ('Nest', 'other');
insert into devices (name, cat) values ('Ring', 'other');
insert into devices (name, cat) values ('Fridge', 'other');
insert into devices (name, cat) values ('Bathroom Scale', 'other');
insert into devices (name, cat) values ('Bathroom Toothbrush', 'other');
insert into devices (name, cat) values ('Bathroom Mirror', 'other');
insert into devices (name, cat) values ('Coffee', 'other');
insert into devices (name, cat) values ('Pet Feeder', 'other');
insert into devices (name, cat) values ('Andrew iPhone', 'other');
insert into devices (name, cat) values ('Jen iPhone', 'other');
insert into devices (name, cat) values ('Jordan iPhone', 'other');
insert into devices (name, cat) values ('Jason iPhone', 'other');
insert into devices (name, cat) values ('Athena iPad', 'other');
insert into devices (name, cat) values ('Austin iPad', 'other');
insert into devices (name, cat) values ('Playstation', 'other');
insert into devices (name, cat) values ('X-Box', 'other');
insert into devices (name, cat) values ('Alexa', 'other');
insert into devices (name, cat) values ('Small Speaker', 'other');
insert into devices (name, cat) values ('2022 MacBook Air', 'other');
insert into devices (name, cat) values ('2020 MacBook Pro', 'other');
insert into devices (name, cat) values ('2021 iMac', 'other');
insert into devices (name, cat) values ('Rouge Bad Guy Device', 'other');
