insert into devices (name, cat, guid) values ('Living Room TV', 'other', '9901');
insert into devices (name, cat, guid) values ('Bedroom TV', 'other', '8901');
insert into devices (name, cat, guid) values ('Tesla 2017 Red', 'other', '0001');
insert into devices (name, cat, guid) values ('Tesla 2019 White', 'other', '0002');
insert into devices (name, cat, guid) values ('iBike e-Assist', 'other', '0003');
insert into devices (name, cat, guid) values ('Nest', 'other', '0004');
insert into devices (name, cat, guid) values ('Ring', 'other', '0005');
insert into devices (name, cat, guid) values ('Fridge', 'other', '0006');
insert into devices (name, cat, guid) values ('Bathroom Scale', 'other', '0007');
insert into devices (name, cat, guid) values ('Bathroom Toothbrush', 'other', '0008');
insert into devices (name, cat, guid) values ('Bathroom Mirror', 'other', '0009');
insert into devices (name, cat, guid) values ('Coffee', 'other', '1003');
insert into devices (name, cat, guid) values ('Pet Feeder', 'other', '2003');
insert into devices (name, cat, guid) values ('Andrew iPhone', 'other', '3003');
insert into devices (name, cat, guid) values ('Jen iPhone', 'other', '4003');
insert into devices (name, cat, guid) values ('Jordan iPhone', 'other', '5003');
insert into devices (name, cat, guid) values ('Jason iPhone', 'other', '6003');
insert into devices (name, cat, guid) values ('Athena iPad', 'other', '7003');
insert into devices (name, cat, guid) values ('Austin iPad', 'other', '8003');
insert into devices (name, cat, guid) values ('Playstation', 'other', '9003');
insert into devices (name, cat, guid) values ('X-Box', 'other', '0103');
insert into devices (name, cat, guid) values ('Alexa', 'other', '0203');
insert into devices (name, cat, guid) values ('Small Speaker', 'other', '0303');
insert into devices (name, cat, guid) values ('2022 MacBook Air', 'other', '0403');
insert into devices (name, cat, guid) values ('2020 MacBook Pro', 'other', '0503');
insert into devices (name, cat, guid) values ('2021 iMac', 'other', '0603');
insert into devices (name, cat, guid) values ('Rouge Bad Guy Device', 'other', '0703');
