insert into devices (name, cat, guid) values ('Living Room TV', 'other', '9901');
insert into devices (name, cat, guid) values ('Bedroom TV', 'other', '8901');
insert into devices (name, cat, guid) values ('Tesla 2017 Red', 'other', '0001');
insert into devices (name, cat, guid) values ('Tesla 2019 White', 'other', '0002');
insert into devices (name, cat, guid) values ('iBike e-Assist', 'other', '0003');
insert into devices (name, cat, guid) values ('Nest', 'other', '0004');
insert into devices (name, cat, guid) values ('Ring', 'other', '0005');
insert into devices (name, cat, guid) values ('Fridge', 'other', '0006');
insert into devices (name, cat, guid) values ('Bathroom Scale', 'other', '0007');
insert into devices (name, cat, guid) values ('Bathroom Toothbrush', 'other', '0008');
insert into devices (name, cat, guid) values ('Bathroom Mirror', 'other', '0009');
insert into devices (name, cat, guid) values ('Coffee', 'other', '1003');
insert into devices (name, cat, guid) values ('Pet Feeder', 'other', '2003');
insert into devices (name, cat, guid) values ('Andrew iPhone', 'other', '3003');
insert into devices (name, cat, guid) values ('Jen iPhone', 'other', '4003');
insert into devices (name, cat, guid) values ('Jordan iPhone', 'other', '5003');
insert into devices (name, cat, guid) values ('Jason iPhone', 'other', '6003');
insert into devices (name, cat, guid) values ('Athena iPad', 'other', '7003');
insert into devices (name, cat, guid) values ('Austin iPad', 'other', '8003');
insert into devices (name, cat, guid) values ('Playstation', 'other', '9003');
insert into devices (name, cat, guid) values ('X-Box', 'other', '0103');
insert into devices (name, cat, guid) values ('Alexa', 'other', '0203');
insert into devices (name, cat, guid) values ('Small Speaker', 'other', '0303');
insert into devices (name, cat, guid) values ('2022 MacBook Air', 'other', '0403');
insert into devices (name, cat, guid) values ('2020 MacBook Pro', 'other', '0503');
insert into devices (name, cat, guid) values ('2021 iMac', 'other', '0603');
insert into devices (name, cat, guid) values ('Rouge Bad Guy Device', 'other', '0703');

insert into functions (device_id, function) values (36, 'release_food(bay,grams)');
insert into functions (device_id, function) values (36, 'play_audio(file)');
insert into functions (device_id, function) values (36, 'take_photo');

insert into functions (device_id, function) values (31, 'take_photo');
insert into functions (device_id, function) values (31, 'play_audio(file)');
insert into functions (device_id, function) values (31, 'set_temperature(celsius)');
insert into functions (device_id, function) values (31, 'set_temperature(fahrenheit)');

insert into payloads (device_id, payload) values (36, '{"bays": [ {"id": "BAY_01", "sku": "MEOW_MIX_1010", "flavor": "Chicken and Yumminess", "grams": 2000}, {"id": "BAY_02", "sku": "MEOW_MIX_1020", "flavor": "Fresh Sardines", "grams": 1900} ] }');
insert into payloads (device_id, payload) values (36, '{"photo": "https://i.imgur.com/M4UMA2Z.png"}'); 
insert into payloads (device_id, payload) values (31, '{ "fridgeId": "SFR123456", "model": "SmartFreeze 9000", "temperature": 2.5, "humidity": 45, "status": "operational", "lastUpdate": "2023-12-16T08:30:00Z", "inventory": [ { "item": "Milk", "quantity": 2, "expiryDate": "2023-12-20" }, { "item": "Eggs", "quantity": 1, "expiryDate": "2023-12-18" }, { "item": "Yogurt", "quantity": 3, "expiryDate": "2023-12-22" }, { "item": "Cheese", "quantity": 1, "expiryDate": "2023-12-25" }, { "item": "Vegetables", "quantity": 5, "expiryDate": null } ], "energyConsumption": { "current": 120, "average": 100, "unit": "Watt-hours" }, "alerts": [ { "type": "temperature", "message": "Temperature is higher than usual. Check settings." }, { "type": "inventory", "message": "Low quantity of eggs. Consider restocking." } ], "settings": { "temperatureUnit": "Celsius", "humidityAlertThreshold": 50 } }');
insert into payloads (device_id, payload) values (31, '{"photo": "https://i.imgur.com/No5lsDm.png"}'); 
insert into payloads (device_id, payload) values (37, '{ "device_info": { "device_name": "Andrew iPhone", "model": "iPhone SE", "os_version": "iOS 15.3", "serial_number": "1234567890", "battery": { "battery_percentage": 75, "battery_status": "Charging", "charging_source": "Lightning Cable" }, "storage": { "total_storage": "128 GB", "available_storage": "64 GB", "used_storage": "64 GB" } }, "system_status": { "cpu_usage": "25%", "memory": { "total_memory": "4 GB", "used_memory": "2 GB", "free_memory": "2 GB" }, "network": { "wifi": { "status": "Connected", "signal_strength": "Excellent" }, "cellular": { "status": "4G", "signal_strength": "High" } } }, "apps": { "running_apps": [ { "name": "Safari", "status": "Active", "cpu_usage": "10%", "memory_usage": "150 MB" }, { "name": "Messages", "status": "Inactive", "cpu_usage": "5%", "memory_usage": "80 MB" }, { "name": "Music", "status": "Active", "cpu_usage": "8%", "memory_usage": "120 MB" } ] }, "security": { "face_id": { "enabled": false }, "touch_id": { "enabled": true }, "passcode": { "enabled": true, "complexity": "Medium" } } }');
